// <auto-generated />
using System;
using ConectMaster.Bancodedados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConectMaster.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724170538_commax")]
    partial class commax
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConectMaster.Models.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("ConectMaster.Models.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("ConectMaster.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Perfis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        });
                });

            modelBuilder.Entity("ConectMaster.Models.PerfilPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("PerfilPermissoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PerfilId = 1,
                            PermissaoId = 1
                        },
                        new
                        {
                            Id = 2,
                            PerfilId = 1,
                            PermissaoId = 2
                        },
                        new
                        {
                            Id = 3,
                            PerfilId = 1,
                            PermissaoId = 3
                        },
                        new
                        {
                            Id = 4,
                            PerfilId = 1,
                            PermissaoId = 4
                        },
                        new
                        {
                            Id = 5,
                            PerfilId = 1,
                            PermissaoId = 5
                        },
                        new
                        {
                            Id = 6,
                            PerfilId = 1,
                            PermissaoId = 6
                        },
                        new
                        {
                            Id = 7,
                            PerfilId = 1,
                            PermissaoId = 7
                        },
                        new
                        {
                            Id = 8,
                            PerfilId = 1,
                            PermissaoId = 8
                        },
                        new
                        {
                            Id = 9,
                            PerfilId = 1,
                            PermissaoId = 9
                        },
                        new
                        {
                            Id = 10,
                            PerfilId = 1,
                            PermissaoId = 10
                        },
                        new
                        {
                            Id = 11,
                            PerfilId = 1,
                            PermissaoId = 11
                        },
                        new
                        {
                            Id = 12,
                            PerfilId = 1,
                            PermissaoId = 12
                        },
                        new
                        {
                            Id = 13,
                            PerfilId = 1,
                            PermissaoId = 13
                        },
                        new
                        {
                            Id = 14,
                            PerfilId = 1,
                            PermissaoId = 14
                        },
                        new
                        {
                            Id = 15,
                            PerfilId = 1,
                            PermissaoId = 15
                        },
                        new
                        {
                            Id = 16,
                            PerfilId = 1,
                            PermissaoId = 16
                        },
                        new
                        {
                            Id = 17,
                            PerfilId = 1,
                            PermissaoId = 17
                        },
                        new
                        {
                            Id = 18,
                            PerfilId = 1,
                            PermissaoId = 18
                        },
                        new
                        {
                            Id = 19,
                            PerfilId = 1,
                            PermissaoId = 19
                        },
                        new
                        {
                            Id = 20,
                            PerfilId = 1,
                            PermissaoId = 20
                        },
                        new
                        {
                            Id = 21,
                            PerfilId = 1,
                            PermissaoId = 21
                        },
                        new
                        {
                            Id = 22,
                            PerfilId = 1,
                            PermissaoId = 22
                        },
                        new
                        {
                            Id = 23,
                            PerfilId = 1,
                            PermissaoId = 23
                        },
                        new
                        {
                            Id = 24,
                            PerfilId = 1,
                            PermissaoId = 24
                        },
                        new
                        {
                            Id = 25,
                            PerfilId = 1,
                            PermissaoId = 25
                        },
                        new
                        {
                            Id = 26,
                            PerfilId = 1,
                            PermissaoId = 26
                        },
                        new
                        {
                            Id = 27,
                            PerfilId = 1,
                            PermissaoId = 27
                        });
                });

            modelBuilder.Entity("ConectMaster.Models.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Visualizar chamados"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Criar chamados"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Editar chamados"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Apagar chamados"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Visualizar historicos"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Editar historicos"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Apagar historicos"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Visualizar permissoes"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Criar permissoes"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Editar permissoes"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Apagar permissoes"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Visualizar perfis"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Criar perfis"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Editar perfis"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Apagar perfis"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Visualizar usuarios"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Criar Usuario"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Editar usuarios"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Apagar usuarios"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Visualizar perfilviews"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Criar usuarioviews"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Apagar perfilviews"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Apagar usuarioviws"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Visualizar views"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Criar servico"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Visualizar servicos"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Autorizar ou Negar OS"
                        });
                });

            modelBuilder.Entity("ConectMaster.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClienteContato")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClienteDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClienteNome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClienteTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataColeta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("DescricaoCarga")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EnderecoColeta")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("EnderecoEntrega")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MotoristaNome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MotoristaTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NaturezaCarga")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroCte")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroNfe")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("PesoBruto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PlacaVeiculo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<int?>("QtdVolumes")
                        .HasColumnType("int");

                    b.Property<string>("Setor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoVeiculo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("ValorFrete")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ValorMercadoria")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("ConectMaster.Models.UsuarioView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ViewId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ViewId");

                    b.ToTable("UsuarioView");
                });

            modelBuilder.Entity("ConectMaster.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Ramal")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Senha")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Setor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ConectMaster.Models.Views", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Views");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "visual.abrirchamado"
                        },
                        new
                        {
                            Id = 2,
                            Name = "visual.ordemservico"
                        },
                        new
                        {
                            Id = 3,
                            Name = "visual.historicochamados"
                        },
                        new
                        {
                            Id = 4,
                            Name = "visual.painelcontrole"
                        },
                        new
                        {
                            Id = 5,
                            Name = "visual.abriruber"
                        },
                        new
                        {
                            Id = 6,
                            Name = "visual.geralusuarios"
                        },
                        new
                        {
                            Id = 7,
                            Name = "visual.permissoes"
                        },
                        new
                        {
                            Id = 8,
                            Name = "visual.relatorios"
                        },
                        new
                        {
                            Id = 9,
                            Name = "visual.logs"
                        },
                        new
                        {
                            Id = 10,
                            Name = "visual.configuracoes"
                        },
                        new
                        {
                            Id = 11,
                            Name = "visual.servicosgeral"
                        });
                });

            modelBuilder.Entity("ConectMaster.Models.chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idUsuario");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("ConectMaster.Models.Historico", b =>
                {
                    b.HasOne("ConectMaster.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConectMaster.Models.PerfilPermissao", b =>
                {
                    b.HasOne("ConectMaster.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectMaster.Models.Permissao", "Permissao")
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("ConectMaster.Models.UsuarioView", b =>
                {
                    b.HasOne("ConectMaster.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectMaster.Models.Views", "View")
                        .WithMany()
                        .HasForeignKey("ViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("View");
                });

            modelBuilder.Entity("ConectMaster.Models.Usuarios", b =>
                {
                    b.HasOne("ConectMaster.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("ConectMaster.Models.chamado", b =>
                {
                    b.HasOne("ConectMaster.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
